{
 "title": "Grafana",
 "description": "Grafana Internal Metrics Dashboards",
 "tags": [
  "grafana",
  "internal metrics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(grafana_stat_total_orgs,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Users",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Admins",
   "type": "stat",
   "description": "Total amount of Admins",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_admins{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "total amount of alerts",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_alerting_alerts{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Grafana Up",
   "type": "timeseries",
   "description": "Show if instance us Up or Down. Default Prometheus Metric.\n\nIf target is not reachable this will have 0 value",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts State",
     "type": "stat",
     "description": "State of the Alerts in orgs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafana_alerting_alerts{instance=\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Alerts State",
     "type": "timeseries",
     "description": "State of the Alerts in orgs",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "increase(grafana_alerting_alerts{instance=\"$instance\"}[$__interval]) > 0",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  {
   "title": "Responce Codes and Logins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Response Statuses",
     "type": "bargauge",
     "description": "http response status",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(grafana_api_response_status_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "API {{ code }}"
      },
      {
       "expr": "increase(grafana_page_response_status_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "Page {{ code }}"
      },
      {
       "expr": "increase(grafana_proxy_response_status_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "Proxy {{ code }}"
      }
     ]
    },
    {
     "title": "Total Response Statuses",
     "type": "timeseries",
     "description": "http response status",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(grafana_api_response_status_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "API {{ code }}"
      },
      {
       "expr": "increase(grafana_page_response_status_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "Page {{ code }}"
      },
      {
       "expr": "increase(grafana_proxy_response_status_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "Proxy {{ code }}"
      }
     ]
    },
    {
     "title": "Login Counts",
     "type": "timeseries",
     "description": "api login counters",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafana_api_login_post_total{instance=\"$instance\"}",
       "legendFormat": "POST"
      },
      {
       "expr": "grafana_api_login_oauth_total{instance=\"$instance\"}",
       "legendFormat": "OAuth"
      }
     ]
    }
   ]
  }
 ]
}