{
 "title": "Prometheus",
 "description": "Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Ready",
   "type": "stat",
   "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Configuration Reload",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Number of scrape pool targets.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets{instance=\"$instance\"})",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "Total user and system CPU time.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rule Execution",
   "type": "stat",
   "description": "The maximum p99 duration for a rule to execute.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Oldest Value",
   "type": "stat",
   "description": "Oldest timestamp value stored in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(prometheus_tsdb_lowest_timestamp_seconds)-prometheus_tsdb_lowest_timestamp_seconds{instance=\"$instance\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "stat",
   "description": "State of the query log.\nhttps://prometheus.io/docs/guides/query-log/",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_query_log_enabled{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Configuration Reload Time",
   "type": "stat",
   "description": "Last successful configuration reload.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Resident memory size.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluation",
   "type": "stat",
   "description": "The maximum p99 duration of rule group evaluations.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_group_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "The current number of queries being executed or waiting.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_queries{instance=\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Log Failures",
   "type": "stat",
   "description": "The number of query log failures.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_log_failures_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Open"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Prometheus CPU Usage %",
   "type": "timeseries",
   "description": "Total user and system CPU time of Prometheus process.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus RAM Usage",
   "type": "timeseries",
   "description": "Resident memory size of Prometheus process",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Targets per Job",
   "type": "stat",
   "description": "Current number of targets in this scrape pool.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pool_targets{instance=\"$instance\"}",
     "legendFormat": "{{ scrape_job }}"
    }
   ]
  },
  {
   "title": "Actual Intervals between Scrapes (p99)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ interval }}"
    }
   ]
  },
  {
   "title": "Sync Interval",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_target_sync_length_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  { "title": "Rule Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Rule Execution Time",
   "type": "timeseries",
   "description": "The duration for a rule to execute.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluation Time",
   "type": "timeseries",
   "description": "The duration of rule group evaluations.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_group_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Rule Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "prometheus_rule_group_rules{instance=\"$instance\"}",
     "legendFormat": "# of rules"
    },
    {
     "expr": "prometheus_rule_group_last_evaluation_samples{instance=\"$instance\"}",
     "legendFormat": "Samples"
    },
    {
     "expr": "prometheus_rule_group_last_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Last duration"
    },
    {
     "expr": "increase(prometheus_rule_group_iterations_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Iterations"
    },
    {
     "expr": "prometheus_rule_group_interval_seconds{instance=\"$instance\"}",
     "legendFormat": "Interval"
    },
    {
     "expr": "increase(prometheus_rule_group_iterations_missed_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Missed"
    },
    {
     "expr": "increase(prometheus_rule_evaluations_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Rule Evaluations"
    },
    {
     "expr": "increase(prometheus_rule_evaluation_failures_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Failed Evaluations"
    }
   ]
  }
 ]
}